export default {
  siteName: "LZArt",
  siteDescription: "Be simple",
  contatEmail: "contato@lzart.com.br",
  siteLogo: "/logo.webp",
  bgImage: "/bg.webp",
  projects: [
    {
      title: "Tarefa Educação",
      url: "https://tarefaedu.lzart.com.br",
      technology: "SvelteKit",
      tooltip: "O seu site de atividades pedagógicas!",
      preview: "/previews/tarefa-educacao.webp",
    },
    {
      title: "Drop",
      url: "https://drop.lzart.com.br",
      technology: "SvelteKit",
      tooltip: "Transferências de arquivos na velocidade máxima!",
      preview: "/previews/drop.webp",
    },
    {
      title: "SyncView",
      url: "https://syncview.lzart.com.br",
      technology: "SvelteKit",
      tooltip: "Assista vídeo sincronizado!",
      preview: "/previews/syncview.webp",
    },
    {
      title: "SoundSync",
      url: "https://soundsync.lzart.com.br",
      technology: "SvelteKit",
      tooltip: "Sincronize músicas com amigos!",
      preview: "/previews/soundsync.webp",
    },
    {
      title: "Banger",
      url: "https://banger.lzart.com.br",
      technology: "Vanilla TS",
      tooltip: "BANGs de buscas instantâneas!",
      preview: "/previews/banger.webp",
    },
    {
      title: "Shortener",
      url: "https://s.lzart.com.br",
      technology: "SvelteKit",
      tooltip: "Encurtadores de links instantâneos!",
    },
    {
      title: "QREncode",
      url: "https://qrcode.lzart.com.br",
      technology: "SvelteKit",
      tooltip: "Gerador de QR Codes 100% offline!",
      preview: "/previews/qrencode.webp",
    },
    {
      title: "BGRemover",
      url: "https://bgremover.lzart.com.br",
      technology: "SvelteKit/Static",
      tooltip: "Remova o fundo de imagens, 100% gratuito!",
      preview: "/previews/bgremover.webp",
    },
    {
      title: "WALink Generator",
      url: "https://walink.lzart.com.br",
      technology: "Svelte",
      tooltip: "Gerador de links de WhatsApp!",
      preview: "/previews/walink-generator.webp",
    },
    {
      title: "BPM Calculator",
      url: "https://bpm.lzart.com.br",
      technology: "Vue",
      tooltip: "Calculadora de BPM!",
    },
    {
      title: "Terraria Class Setups",
      url: "https://terraria.lzart.com.br",
      technology: "Vue",
      tooltip: "Classes para o Terraria!",
    },
    {
      title: "Oficina RogerNight",
      url: "https://ofrgnight.github.io",
      technology: "Nuxt/Static",
      tooltip: "A melhor oficina da região!",
      preview: "/previews/oficina-rogernight.webp",
    },
    {
      title: "NGMaker",
      url: "https://ngmaker.com.br",
      technology: "SvelteKit",
      tooltip: "A melhor em publicidade!",
    },
    {
      title: "Whoami",
      url: "https://luis.lzart.com.br/",
      technology: "Nuxt/Static",
      tooltip: "Meu currículo digital!",
      preview: "/previews/whoami.webp",
    },
  ],
  packages: [
    {
      title: "Desfetch",
      url: "https://npmx.dev/package/desfetch",
      technology: "TypeScript",
      tooltip:
        "Wrapper type-safe do fetch com { data, error } e JSON automático.",
      preview: "/previews/npm.webp",
    },
    {
      title: "FastRTC",
      url: "https://npmx.dev/package/fastrtc",
      technology: "TypeScript",
      tooltip: "Helper de mesh para conectar peers e abrir data channels.",
      preview: "/previews/npm.webp",
    },
    {
      title: "Quick DI",
      url: "https://npmx.dev/package/quick-di",
      technology: "TypeScript",
      tooltip:
        "Injeção de dependência mínima e rápida. inject(), sem decorators.",
      preview: "/previews/npm.webp",
    },
    {
      title: "Svelte Lazyloader",
      url: "https://npmx.dev/package/svelte-comp-lazyloader",
      technology: "TypeScript",
      tooltip:
        "Lazy-load de componentes Svelte 5 com props tipadas, preload e SSR.",
      preview: "/previews/npm.webp",
    },
    {
      title: "SvelteKit Node Worker",
      url: "https://npmx.dev/package/vite-plugin-sveltekit-node-worker",
      technology: "TypeScript",
      tooltip:
        "Plugin Vite para worker_threads do Node.js no SvelteKit 3.",
      preview: "/previews/npm.webp",
    },
    {
      title: "SvelteKit WS",
      url: "https://npmx.dev/package/vite-plugin-sveltekit-ws",
      technology: "TypeScript",
      tooltip:
        "Plugin Vite que adiciona suporte a WebSocket no SvelteKit com adapter-node.",
      preview: "/previews/npm.webp",
    },
    {
      title: "Typed SW",
      url: "https://npmx.dev/package/vite-plugin-typed-sw",
      technology: "TypeScript",
      tooltip: "Plugin Vite para Service Workers ESM type-safe com HMR.",
      preview: "/previews/npm.webp",
    },
  ],
};
